USE TravelAgency_TJL
GO

IF OBJECT_ID('DestinatioNo_INSERT_DELETE') IS NOT NULL
 DROP TRIGGER DestinatioNo_INSERT_DELETE
GO
CREATE TRIGGER DestinatioNo_INSERT_DELETE
 ON Travel
 AFTER INSERT,DELETE
AS
 DELETE Travel
WHERE DestinationNo >= 6
GO
